import argparse
import os
import sqlite3
from pathlib import Path


TYPE_MAP = {
    "INT": "BIGINT",
    "INTEGER": "BIGINT",
    "REAL": "DOUBLE PRECISION",
    "FLOA": "DOUBLE PRECISION",
    "DOUB": "DOUBLE PRECISION",
    "NUM": "NUMERIC",
    "DEC": "NUMERIC",
    "BOOL": "BOOLEAN",
    "BLOB": "BYTEA",
    "TEXT": "TEXT",
    "CHAR": "TEXT",
    "CLOB": "TEXT",
}


def quote_ident(name: str) -> str:
    return '"' + name.replace('"', '""') + '"'


def quote_literal(value):
    if value is None:
        return "NULL"
    if isinstance(value, bool):
        return "TRUE" if value else "FALSE"
    if isinstance(value, (int, float)):
        return str(value)
    if isinstance(value, bytes):
        return f"'\\x{value.hex()}'::bytea"
    return "'" + str(value).replace("'", "''") + "'"


def postgres_type(declared_type: str, is_pk: bool, column_name: str) -> str:
    upper = (declared_type or "").upper()
    for marker, pg_type in TYPE_MAP.items():
        if marker in upper:
            if is_pk and pg_type == "BIGINT" and column_name in {"id", "log_id", "run_id"}:
                return "BIGINT GENERATED BY DEFAULT AS IDENTITY"
            return pg_type
    if is_pk and column_name in {"id", "log_id", "run_id"}:
        return "BIGINT GENERATED BY DEFAULT AS IDENTITY"
    return "TEXT"


def sqlite_default_to_postgres(default_value):
    if default_value is None:
        return None
    value = str(default_value).strip()
    if not value:
        return None
    upper = value.upper()
    if upper in {"CURRENT_TIMESTAMP", "CURRENT_DATE", "CURRENT_TIME"}:
        return upper
    return value


def table_names(conn: sqlite3.Connection):
    cur = conn.cursor()
    return [
        row[0]
        for row in cur.execute(
            "SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%' ORDER BY name"
        )
    ]


def table_columns(conn: sqlite3.Connection, table_name: str):
    cur = conn.cursor()
    rows = cur.execute(f"PRAGMA table_info({quote_ident(table_name)})").fetchall()
    return [
        {
            "name": row[1],
            "type": row[2] or "TEXT",
            "notnull": bool(row[3]),
            "default": row[4],
            "pk": bool(row[5]),
        }
        for row in rows
    ]


def create_table_sql(conn: sqlite3.Connection, table_name: str):
    columns = table_columns(conn, table_name)
    parts = []
    for column in columns:
        fragment = [quote_ident(column["name"]), postgres_type(column["type"], column["pk"], column["name"])]
        if column["pk"]:
            fragment.append("PRIMARY KEY")
        if column["notnull"]:
            fragment.append("NOT NULL")
        default = sqlite_default_to_postgres(column["default"])
        if default is not None:
            fragment.append(f"DEFAULT {default}")
        parts.append(" ".join(fragment))
    joined = ",\n  ".join(parts)
    return f"CREATE TABLE {quote_ident(table_name)} (\n  {joined}\n);"


def table_row_count(conn: sqlite3.Connection, table_name: str) -> int:
    cur = conn.cursor()
    return cur.execute(f"SELECT COUNT(*) FROM {quote_ident(table_name)}").fetchone()[0]


def select_all_rows(conn: sqlite3.Connection, table_name: str):
    conn.row_factory = sqlite3.Row
    cur = conn.cursor()
    return cur.execute(f"SELECT * FROM {quote_ident(table_name)}").fetchall()


def sequence_fix_sql(conn: sqlite3.Connection, table_name: str):
    statements = []
    for column in table_columns(conn, table_name):
        if column["pk"] and column["name"] in {"id", "log_id", "run_id"}:
            statements.append(
                "SELECT setval(pg_get_serial_sequence({table}, {column}), "
                "COALESCE((SELECT MAX({col_ident}) FROM {table_ident}), 1), true);".format(
                    table=quote_literal(table_name),
                    column=quote_literal(column["name"]),
                    col_ident=quote_ident(column["name"]),
                    table_ident=quote_ident(table_name),
                )
            )
    return statements


def insert_sql(conn: sqlite3.Connection, table_name: str):
    rows = select_all_rows(conn, table_name)
    if not rows:
        return []
    column_names = rows[0].keys()
    quoted_columns = ", ".join(quote_ident(name) for name in column_names)
    statements = []
    for row in rows:
        values = ", ".join(quote_literal(row[name]) for name in column_names)
        statements.append(f"INSERT INTO {quote_ident(table_name)} ({quoted_columns}) VALUES ({values});")
    return statements


def build_dump(sqlite_path: Path, dump_path: Path):
    conn = sqlite3.connect(sqlite_path)
    try:
        lines = [
            "BEGIN;",
            "",
        ]
        for table_name in table_names(conn):
            lines.append(f"DROP TABLE IF EXISTS {quote_ident(table_name)} CASCADE;")
        lines.append("")
        for table_name in table_names(conn):
            lines.append(create_table_sql(conn, table_name))
            lines.append("")
        for table_name in table_names(conn):
            lines.extend(insert_sql(conn, table_name))
            lines.append("")
        for table_name in table_names(conn):
            lines.extend(sequence_fix_sql(conn, table_name))
        lines.append("")
        lines.append("COMMIT;")
        dump_path.write_text("\n".join(lines), encoding="utf-8")
        return {table_name: table_row_count(conn, table_name) for table_name in table_names(conn)}
    finally:
        conn.close()


def load_dump(postgres_dsn: str, dump_path: Path):
    try:
        import psycopg
    except ImportError as exc:
        raise SystemExit("psycopg is required. Install it with: pip install psycopg[binary]") from exc

    sql_text = dump_path.read_text(encoding="utf-8")
    dsn = postgres_dsn
    if "sslmode=" not in dsn:
        separator = "&" if "?" in dsn else "?"
        dsn = f"{dsn}{separator}sslmode=require"
    with psycopg.connect(dsn) as conn:
        with conn.cursor() as cur:
            cur.execute(sql_text)
        conn.commit()


def verify_counts(postgres_dsn: str, expected_counts: dict):
    try:
        import psycopg
    except ImportError as exc:
        raise SystemExit("psycopg is required. Install it with: pip install psycopg[binary]") from exc

    dsn = postgres_dsn
    if "sslmode=" not in dsn:
        separator = "&" if "?" in dsn else "?"
        dsn = f"{dsn}{separator}sslmode=require"
    actual = {}
    with psycopg.connect(dsn) as conn:
        with conn.cursor() as cur:
            for table_name in expected_counts:
                cur.execute(f"SELECT COUNT(*) FROM {quote_ident(table_name)}")
                actual[table_name] = cur.fetchone()[0]
    return actual


def main():
    parser = argparse.ArgumentParser(description="Migrate SQLite data to PostgreSQL and emit a SQL dump.")
    parser.add_argument("--sqlite", default=str(Path(__file__).with_name("lms.db")))
    parser.add_argument("--dump", default=str(Path(__file__).with_name("sqlite_to_postgres_dump.sql")))
    parser.add_argument("--postgres-dsn", default=os.environ.get("TARGET_POSTGRES_DSN", ""))
    args = parser.parse_args()

    sqlite_path = Path(args.sqlite)
    dump_path = Path(args.dump)
    if not sqlite_path.exists():
        raise SystemExit(f"SQLite database not found: {sqlite_path}")

    expected_counts = build_dump(sqlite_path, dump_path)
    print(f"Created dump file: {dump_path}")
    print(f"Source counts: {expected_counts}")

    if args.postgres_dsn:
        load_dump(args.postgres_dsn, dump_path)
        actual_counts = verify_counts(args.postgres_dsn, expected_counts)
        print(f"Target counts: {actual_counts}")
        if actual_counts != expected_counts:
            raise SystemExit("Row count verification failed after import")


if __name__ == "__main__":
    main()
